name: CI/CD

on: 
  push:
    branches: ['*']

jobs:
  check-docker-compose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    - name: Validate docker-compose.yml
      run: docker-compose config

    - name: Test services
      run: |
        docker-compose up -d
        sleep 5
        docker-compose ps
        docker-compose down