name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Test Docker
      run: |
        docker --version
        docker compose version
        docker run hello-world
        
    - name: Build and test
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose ps
        docker-compose down